version: "3.8"
services:
  user_movies_db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: 'api-user'
      POSTGRES_USER: 'api-user'
      POSTGRES_DB: 'UsersMovies'

  movie_api:
    build: ./movies_api
    entrypoint: ['/bin/bash', '-c', '/run.sh']
    environment:
      POSTGRES_PASSWORD: 'api-user'
      POSTGRES_USER: 'api-user'
      POSTGRES_DB: 'UsersMovies'
      POSTGRES_HOST: user_movies_db
      POSTGRES_PORT: 5432
    volumes:
      - ~/movies_app:/movies_app
    depends_on:
      - user_movies_db
    links:
      - user_movies_db:user_movies_db
